USE [Nikita's Car Rental Company];
GO


-- 1
SELECT PICKUP_LOCATION,COUNT(*) AS RENTALS ,CONCAT(YEAR(RENTAL_DATE),'-',MONTH(RENTAL_DATE),'-',DAY(RENTAL_DATE)) AS DAY_WINDOW
FROM Rentals
GROUP BY PICKUP_LOCATION, CONCAT(YEAR(RENTAL_DATE),'-',MONTH(RENTAL_DATE),'-',DAY(RENTAL_DATE))

-- 2
SELECT TOP 10 DATEDIFF(day,RENTAL_DATE,RETURN_DATE) AS TRIP_DURATION, Rentals.RENTAL_ID, Customers.FIRST_NAME, Customers.LAST_NAME
FROM Rentals
INNER JOIN Customers ON Rentals.CUSTOMER_ID = Customers.CUSTOMER_ID
INNER JOIN Cars ON Rentals.VIN_NUMBER = Cars.VIN_NUMBER
WHERE Cars.CAR_TYPE = 'Pickup'
ORDER BY TRIP_DURATION DESC

-- 3
SELECT * FROM Cars
WHERE MILEAGE > (SELECT AVG(MILEAGE) FROM Cars) * 1.5


-- 4
SELECT SUM(count_groupped) as TOTAL_COUNT
FROM (SELECT COUNT(*) AS count_groupped
FROM Rentals 
WHERE PICKUP_LOCATION <> RETURN_LOCATION
GROUP BY CUSTOMER_ID
HAVING SUM(DISTANCE) > 700) as sub_table