USE [Nikita's Car Rental Company];
GO

CREATE TABLE Employees (
EMPLOYEE_ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL
)
CREATE TABLE Cars (
VIN_NUMBER VARCHAR(17) NOT NULL PRIMARY KEY, -- Since 1981, VIN numbers are always composed of 17 digits consisting of numbers and letters. But can be less
MAKE VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
CREATION_YEAR INT NOT NULL,
CAR_TYPE VARCHAR(20) NOT NULL,
CAR_LOCATION VARCHAR(30) NOT NULL,
EMPLOYEE_ID BIGINT NOT NULL FOREIGN KEY REFERENCES Employees(EMPLOYEE_ID),
MILEAGE INT NOT NULL, -- KILOMETERS CAR TRAVELLED OVERALL
AVAILABLE BIT NOT NULL
)

CREATE TABLE Customers (
CUSTOMER_ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
CUSTOMER_ADDRESS VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(50) NOT NULL,
CUSTOMER_EMAIL VARCHAR(50), -- EMAIL IS OPTIONAL
CUSTOMER_CITY VARCHAR(30) NOT NULL,
DISCOUNT DECIMAL(3,2) -- discount may be NULL
)

CREATE TABLE DriverInfo (
DRIVER_LICENSE VARCHAR(30) NOT NULL,
CREDIT_CARD CHAR(16) NOT NULL,
PRIMARY KEY (DRIVER_LICENSE, CREDIT_CARD),
CUSTOMER_ID BIGINT NOT NULL FOREIGN KEY REFERENCES Customers(CUSTOMER_ID)
)

CREATE TABLE PriceList ( -- this table is not connected to any other tables simply because there is no purpose in doing that
PRICELIST_ITEM_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CAR_TYPE VARCHAR(20) NOT NULL,
DAILY_RATE MONEY NOT NULL,
WEEKLY_RATE MONEY NOT NULL,
DAILY_LIMIT INT NOT NULL,
EXTRA_FEE MONEY NOT NULL
)

CREATE TABLE Reservations (
RESERVATION_ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
VIN_NUMBER VARCHAR(17) NOT NULL FOREIGN KEY REFERENCES Cars(VIN_NUMBER),
RESERVATION_DATE DATETIME NOT NULL,
PICKUP_LOCATION VARCHAR(30) NOT NULL,
RETURN_LOCATION VARCHAR(30) NOT NULL,
CUSTOMER_ID BIGINT NOT NULL FOREIGN KEY REFERENCES Customers(CUSTOMER_ID)
)

CREATE TABLE Rentals (
RENTAL_ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
VIN_NUMBER VARCHAR(17) NOT NULL FOREIGN KEY REFERENCES Cars(VIN_NUMBER),
RENTAL_DATE DATETIME NOT NULL,
PICKUP_LOCATION VARCHAR(30) NOT NULL,
RETURN_LOCATION VARCHAR(30) NOT NULL,
CUSTOMER_ID BIGINT NOT NULL FOREIGN KEY REFERENCES Customers(CUSTOMER_ID),
RESTRICTIONS NVARCHAR(MAX),
DISTANCE DECIMAL(9,2) NOT NULL,
RETURN_DATE DATETIME NOT NULL
) 